import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "./useAuth";
import { toast } from "sonner";
export interface StoreProduct { id:string; user_id:string; category_id:string|null; name:string; description:string|null; price:number; image_url:string|null; is_active:boolean; sort_order:number; category_name?:string|null; }
export function useStoreSettings(){const {user}=useAuth();return useQuery({queryKey:["store-settings",user?.id],queryFn:async()=>{if(!user)return null;const {data,error}=await (supabase as any).from("business_settings").select("user_id,business_name,logo_url,primary_color,public_booking_slug,public_booking_enabled,store_enabled,store_show_services,store_show_products,store_whatsapp,store_whatsapp_message").eq("user_id",user.id).maybeSingle();if(error)throw error;return data;},enabled:!!user});}
export function useUpdateStoreSettings(){const {user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(data:any)=>{if(!user)throw new Error("Usuário não autenticado");const {data:r,error}=await supabase.from("business_settings").update(data).eq("user_id",user.id).select().single();if(error)throw error;return r;},onSuccess:()=>{qc.invalidateQueries({queryKey:["store-settings"]});toast.success("Configurações da vitrine salvas!");},onError:(e:any)=>toast.error("Erro ao salvar: "+e.message)});}
export function useStoreProducts(){const {user}=useAuth();return useQuery({queryKey:["store-products",user?.id],queryFn:async()=>{if(!user)return [];const {data,error}=await (supabase as any).from("store_products").select("*").eq("user_id",user.id).order("sort_order").order("name");if(error)throw error;return (data||[]) as StoreProduct[];},enabled:!!user});}
export function useCreateStoreProduct(){const {user}=useAuth();const qc=useQueryClient();return useMutation({mutationFn:async(data:any)=>{if(!user)throw new Error("Usuário não autenticado");const {data:r,error}=await supabase.from("store_products").insert({...data,user_id:user.id}).select().single();if(error)throw error;return r;},onSuccess:()=>{qc.invalidateQueries({queryKey:["store-products"]});toast.success("Produto adicionado!");},onError:(e:any)=>toast.error("Erro: "+e.message)});}
export function useUpdateStoreProduct(){const qc=useQueryClient();return useMutation({mutationFn:async({id,...data}:any)=>{const {data:r,error}=await supabase.from("store_products").update(data).eq("id",id).select().single();if(error)throw error;return r;},onSuccess:()=>{qc.invalidateQueries({queryKey:["store-products"]});toast.success("Produto atualizado!");},onError:(e:any)=>toast.error("Erro: "+e.message)});}
export function useDeleteStoreProduct(){const qc=useQueryClient();return useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("store_products").delete().eq("id",id);if(error)throw error;},onSuccess:()=>{qc.invalidateQueries({queryKey:["store-products"]});toast.success("Produto removido!");},onError:(e:any)=>toast.error("Erro: "+e.message)});}
export function usePublicStore(slug:string){return useQuery({queryKey:["public-store",slug],queryFn:async()=>{const {data:business,error}=await (supabase as any).from("store_public_businesses").select("*").eq("public_booking_slug",slug).maybeSingle();if(error)throw error;if(!business)throw new Error("Vitrine não encontrada");const [productsResult,servicesResult]=await Promise.all([(supabase as any).from("store_public_products").select("*").eq("user_id",business.user_id),supabase.from("services").select("id,name,description,price,duration_minutes").eq("user_id",business.user_id).eq("is_active",true).order("name")]);if(productsResult.error)throw productsResult.error;if(servicesResult.error)throw servicesResult.error;return {business,products:productsResult.data||[],services:servicesResult.data||[]};},enabled:!!slug});}